language: java
sudo: 'required'

jdk:
  - oraclejdk8

services:
  - 'docker'

before_install:
  - 'docker login -u dperezcabrera -p $DOCKER_PASSWORD'

script:
  - mvn clean package
  - docker build -t dperezcabrera/spring-cloud-config-server .
  - docker push dperezcabrera/spring-cloud-config-server

cache:
  directories:
  - "$HOME/.m2"
  
notifications:
  email:
  - dperezcabrera@gmail.com
